### ISSUE TITLE
Not specifying a SQL Dialect in extension settings leads to confusing error

### ISSUE THREAD

**Issue by dsmith7789** [sqlfluff/vscode-sqlfluff#122]
The traceback error given when using the sqlfluff extension is not readily understandable if you don't specify a dialect.
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/61889608/d0135905-8f30-4538-8013-4593a94036ec)

![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/61889608/c984cf79-6f31-4ce8-998c-55ce95de1f72)

Error text ([username] is a placeholder):
Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Scripts\sqlfluff.exe\__main__.py", line 7, in <module> File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__ return self.main(*args, **kwargs) ^^^^^^^^^^^ ^^^^^^^^^^^^^^^ File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\[username]\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434...

After specifying a dialect (ex. ANSI), the error goes away and the extension works as expected.

![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/61889608/21940988-01f8-4beb-8674-fc742cb301f1)
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/61889608/b7a1b3d9-2bc7-4e1f-9697-817716695062)

Result:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/61889608/cb3d4553-e691-4a04-9035-9381c0e14cd5)

**Comment by thijs-nijhuis-shell** [comment]
Hi, just installed this beautiful extension (I worked with it in my previous assignment) and I am getting this exact same error message. Unfortunately, setting the dialect doesn't solve it for me. I set it to both 'databricks' and 'ansi'. Apart from this, I have only set the sqlfluff.executablePath since I have sqlfluff installed in a virtual environment. 
@dsmith7789, do you have any other settings in there that I might need to set as well?
