### ISSUE TITLE
Allow sqlfluff to be installed in a virtualenv

### ISSUE THREAD

**Issue by GClunies** [sqlfluff/vscode-sqlfluff#23]
**Issue:**
As alluded to by @pwildenhain in this [slack thread](https://sqlfluff.slack.com/archives/C01H24EF1NY/p1615396870009000), it seems this extension only works if `sqlfluff` is installed globally. It does not seem to recognize `sqlfluff` when it is installed in a virtual environment.

I have `sqlfluff` installed in a conda virtual environment and I don’t get ANY feedback in VScode that the sqlfluff extension is working even though the extension is installed and enabled. I see no linting hints like in the demo shown in this repo. I am able to run `sqlfluff` from the terminal so I do know it is installed and works.
```bash
▶ sqlfluff lint models/analytics/editorial/sl_web_editorial_time_on_page.sql                                                                                           
== [models/analytics/editorial/sl_web_editorial_time_on_page.sql] FAIL
L:  35 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  37 | P:   5 | L003 | Indent expected and not found compared to line #34
L:  39 | P:   7 | L003 | Indentation not hanging or a multiple of 4 spaces
L:  39 | P: 113 | L016 | Line is too long
```

I have `python`, `dbt`, and `sqlfluff` installed via a `conda` virtual environment (and virtual env is activated in VScode). The conda env is defined as:
```yaml
name: surfline-dbt-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pip:
    - dbt==0.19.0
    - sqlfluff[dbt]
```

Path to `sqlfluff` is
```bash
▶ which sqlfluff                                                                                                                                                    
/opt/anaconda3/envs/surfline-dbt-dev/bin/sqlfluff
```

I have the path to `sqlfluff` specified in my VScode `settings.json` like:
```yaml
    "sql.linter.executablePath": "/opt/anaconda3/envs/surfline-dbt-dev/bin/sqlfluff",
    "sql.linter.run": "onType",
```

**Expected Behavior:**
sqlfluff extension should be able to use `sqlfluff` from the conda environment, or any other virtual environment that is active in VScode.

**Possible Solutions:**
While I am not familiar with the code structure for VScode extensions, I do know that the dbt Power user VSCode extension is able to recognize `dbt` when it is installed in a `conda` environment. Maybe a similar approach could be used here? It _looks_ like the important files for recognizing the virtual environment are listed here: https://github.com/innoverio/vscode-dbt-power-user/search?q=environment

**Comment by RoyalTS** [comment]
Running up against the same issue. Any ongoing work on this?

**Comment by b-per** [comment]
The latest version (0.0.5) fixed the definition of the executable in `"sql.linter.executablePath"`. It doesn't recognise the venv directly but the extension works when the path has been added manually.

**Comment by GClunies** [comment]
@b-per, what do you mean by _"when the path has been added manually"_?

Are you referring to...
![image](https://user-images.githubusercontent.com/28986302/123151151-07cb4e00-d418-11eb-86c4-6ece68bcca3d.png)

because this still doesn't work for me. Would be very interested to know your `venv`l setup and VScode settings.

**Comment by GClunies** [comment]
So it seems this is working for me with this configuration.

`vscode-sqlfluff` extension settings:
![image](https://user-images.githubusercontent.com/28986302/123159275-af00b300-d421-11eb-83b9-bff1c71bc998.png)

Not sure why `onSave` works but `onType` doesn't?

VScode settings found in `.vscode/setting.json` located in my dbt project repo, they override any settings in my global vscode `settings.json`.
```json
{
    "python.pythonPath": "/opt/anaconda3/envs/surfline-dbt/bin/python",
    "sql.linter.executablePath": "/opt/anaconda3/envs/surfline-dbt/bin/sqlfluff"
}
```
Hope this helps others. Thank you @dorzey and others for updates to the plugin 🙏🏽 .

**Comment by dorzey** [comment]
@GClunies It would be great if you could raise a PR with the anaconda setup so that I can link it from the README. I'm unfamiliar with anaconda myself.

**Comment by GClunies** [comment]
@dorzey I am not quite sure yet if `vscode-sqlfluff` is picking up my `.sqlfluff` config. I will hold off on a PR until I can say "this config using conda works for me 100%".

Also, it also takes quite a bit of time after saving for linting errors to show up in my dbt SQL files, in the sidebar (red highlight file), and in the `PROBLEMS` section of the VScode terminal bar. Is this because the plugin has to run `sqlfluff lint my_model` in the background after saving?

As for the `conda` environment I am using
```yml
name: surfline-dbt
channels:
  - conda-forge
  - defaults
dependencies:
  - agate=1.6.1
  - pip=20.1.1
  - python=3.8
  - pip:
    - dbt==0.19.1
    - sqlfluff==0.5.3  # I plan to update this
```

**Comment by dorzey** [comment]
Thanks for this. I will try and find time to replicate your setup.

**Comment by SpikyClip** [comment]
I have the same issue where lint warnings are not showing up in the problems pane, but the formatting on save works??? I've tried clean installing, removing all my sqlfluff user settings, toggling them on/off. Here are my sql related settings:

```
    "[sql]": {
        "editor.defaultFormatter": "dorzey.vscode-sqlfluff"
    },
    "sql.linter.executablePath": "C:\\Users\\Vikesh\\miniconda3\\Scripts\\sqlfluff.exe",
    "files.associations": {
        "*.sql": "sql"
    },
```

Whats strange is the linting was working yesterday, and I had not changed any settings. So I have no clue why its not working today. I have the sqltools extension too but uninstalling that makes no difference either.

I'm on vscode-sqlfluff v0.0.5 and sqlfluff 0.6.6.

**Comment by dbrtly-ofx** [comment]
Somehow, I eventually had this working on a previous machine. New machine and I can't get the vscode extension to work.
I can successfully lint files from the cli.

in the virtual environment:

(env) % which sqlfluff
/Users/danielbartley/my_project/env/bin/
(env) % sqlfluff --version
sqlfluff, version 0.8.2
(env) % cd '/Users/danielbartley/my_project/env/bin/'
(env) % ls | grep sqlfluff
sqlfluff

.vscode/settings.json
{
    "sql.linter.executablePath": "/Users/danielbartley/my_project/env/bin/",
    "sql.linter.run": "onType"
}


right click on a file, select 'format document' and I get:
"spawn  "/Users/danielbartley/my_project/env/bin/" EACCES"
I don't know what that means.

I wrote a note to myself last time that alternating between onType and onSave was enough to get it unstuck. Doesnt work this time.

I would really appreciate more detailed docs for the setup. Willing to help.

**Comment by lorcan17** [comment]
I'm having a similar issue with using vscode-sqlfluff in an conda virtual environment. 

`sqlfluff fix sql_code.sql --dialect snowflake` works using command line so it's installed correctly.

I've added the below to .vscode/settings.json within project:
`{
    "python.defaultInterpreterPath": "c:/Users/user/Anaconda3/envs/sql_development/python",
    "sqlfluff.executablePath": "c:/Users/user/Anaconda3/envs/sql_development/Scripts/sqlfluff"
}`

And I've also added the below to user settings:
`"sqlfluff.executablePath": "c:/Users/user/Anaconda3/envs/sql_development/Scripts/sqlfluff"`

<details>
  <summary>Click me</summary>
  
This is my environment:

`name: sql_development
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - attrs=22.2.0
  - backports.cached-property=1.0.2
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - chardet=5.1.0
  - click=8.1.3
  - colorama=0.4.6
  - diff-cover=7.3.0
  - exceptiongroup=1.1.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - iniconfig=1.1.1
  - jinja2=3.1.2
  - libffi=3.4.2
  - markupsafe=2.1.1
  - openssl=1.1.1s
  - packaging=22.0
  - pathspec=0.10.3
  - pip=22.3.1
  - pluggy=1.0.0
  - pygments=2.14.0
  - pytest=7.2.0
  - python=3.10.8
  - python_abi=3.10
  - pyyaml=6.0
  - regex=2022.7.9
  - setuptools=65.5.0
  - sqlfluff=1.4.5
  - sqlite=3.40.0
  - tblib=1.7.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tqdm=4.64.1
  - typing=3.10.0.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.8
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.13
`

</details>

**Comment by juls858** [comment]
I am having the same issue as @lorcan17 
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 582, in lint
    result = lnt.lint_paths(
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 1177, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 106, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 59, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 46, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 851, in render_file
    raw_file, config, encoding = self.load_raw_file_and_config(fname, root_config)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 136, in load_raw_file_and_config
    file_config.process_raw_file_for_config(raw_file)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/config.py", line 1068, in process_raw_file_for_config
    self.process_inline_config(raw_line)
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/config.py", line 1060, in process_inline_config
    self.set_value(config_path[:-1], config_path[-1])
  File "/usr/local/Caskroom/miniconda/base/envs/livequery-models/lib/python3.8/site-packages/sqlfluff/core/config.py", line 1007, in set_value
    dict_buff.append(dict_buff[-1][elem])
KeyError: 'capitalisation.keywords'
```
