### ISSUE TITLE
The argument 'file' cannot be empty. Received ''

### ISSUE THREAD

**Issue by jice-lavocat** [sqlfluff/vscode-sqlfluff#78]
**Description**:

Sqlfluff works in the CLI. 
In VSCode, I have the 'onSave' trigger (because I'm using `templater: dbt`). When I look in the Dev Console, I get a warning message about having an empty `file` argument. My intuition is that this is related to some new settings that I haven't well configured, but I can't find which one.

**Using**:

- dbt: 1.3.1
- dbt-bigquery: 1.3.0 
- sqlfluff: 1.4.2
- vscode-sqlfluff: 2.2.0

**Stack trace**:

```
TypeError: The argument 'file' cannot be empty. Received ''
	at new NodeError (node:internal/errors:371:5)
	at normalizeSpawnArguments (node:child_process:517:11)
	at Object.spawn (node:child_process:713:13)
	at vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:14:140
	at new Promise (<anonymous>)
	at SQLFluff.run (vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:8:57)
	at C1.doLint (vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:18:3852)
	at vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:18:3305
	at pe.queue (vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:18:737)
	at y1.<anonymous> (vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:18:1630)
	at vscode-file://vscode-app/Users/jice_lavocat/.vscode/extensions/dorzey.vscode-sqlfluff-2.2.0/out/src/extension.js:18:1151
```

**Comment by RobertOstermann** [comment]
@jice-lavocat Hmm, I haven't seen this error before. Was this happening in v2.0.0 as well, or just v2.2.0? Are you seeing any output in the SQLFluff output channel or is the error just in the dev console?

**Comment by jice-lavocat** [comment]
Hi @RobertOstermann ,

It was a misconfiguration on my end as I expected. I had overwrote a setting in the workspace-based config and didn't notice.
